all: compile run clean

compile:
	@javac -d . *java

run: 	
	@echo "\n---------------------------------\n"
	@echo "Running test..."
	@echo "\n---------------------------------\n"
	@java hw8data.Main
	@echo "\n---------------------------------\n"



clean:
	@rm -f *.class
	

